server:
  port: ${PORT:8085}

spring:
  application:
    name: docflowai-sts-pades-service

management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
